### ISSUE TITLE
Which IDE for React?

### ISSUE THREAD

**Issue by sly8787** [tylermcginnis/react-native-gh-notetaker#1]
Hi Tyler, thank you for this great tutorial. Can you please tell me which IDE you are using?

**Comment by cyprusglobe** [comment]
+1 @tylermcginnis I would like to know the same.

**Comment by anshumanf** [comment]
Looked like he was using Sublime Text.

**Comment by tylermcginnis** [comment]
Just saw this. All my settings can be seen here. https://twitter.com/tylermcginnis33/status/610920794189889536
